// GENERATED by tools/gen/pack.ts — do not edit.
// The questions this pack can ask, and the answer space for each.

export interface SessionOutcome { id: string; label: string; verdict: string; means: string }
export interface SessionQuestion {
  index: number;
  id: string;
  probe: string;
  question: string;
  look_at: string;
  askByDefault: boolean;
  priorStatus: string;
  outcomes: SessionOutcome[];
}

export interface SolveSpec {
  id: string;
  probe: string;
  unit: string;
  direction: 'minimum' | 'maximum';
  from: number;
  to: number;
  tolerance: number;
}

export const CATALOG_REVISION = "rf1fd17a4";
export const SNAPSHOT_VERSION = "1.21.120";
export const QUESTIONS: SessionQuestion[] = [
  {
    "index": 0,
    "id": "entity.container.opens_with_container_type_chest",
    "probe": "container",
    "question": "Does the same entity declaring `container_type: chest` open for a player?",
    "look_at": "Interact with the entity labelled `chest5`, next to the horse one.",
    "askByDefault": true,
    "priorStatus": "CLOSED-NEGATIVE",
    "outcomes": [
      {
        "id": "opens",
        "label": "A container screen opens",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "no_screen",
        "label": "Interacting does nothing",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_entity",
        "label": "The entity is not there",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 1,
    "id": "entity.container.opens_with_container_type_horse",
    "probe": "container",
    "question": "Does a custom entity declaring `container_type: horse` open for a player?",
    "look_at": "Interact with the entity labelled `horse5`. A failure here means \"this recipe does not work\", NOT \"custom containers are impossible\" -- reading it as the latter closes off the only route to an arbitrary-item slot.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "opens",
        "label": "A real container screen opens",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "no_screen",
        "label": "Interacting does nothing",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_entity",
        "label": "The entity is not there to interact with",
        "verdict": "INCONCLUSIVE",
        "means": "Check the automated storage row -- if the spawn failed, this measures nothing."
      }
    ]
  },
  {
    "index": 2,
    "id": "entity.container.preview_panel_renders_the_entity",
    "probe": "container",
    "question": "Does the container screen's preview panel draw the entity's own model?",
    "look_at": "The left-hand panel of the open container screen. Move the cursor across it.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "renders_and_tracks",
        "label": "It draws the entity, and it turns to follow the cursor",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "renders_static",
        "label": "It draws the entity but does not track",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "empty",
        "label": "No preview panel, or an empty one",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "could_not_open",
        "label": "Could not open it",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 3,
    "id": "entity.container.screen_draws_declared_slot_count",
    "probe": "container",
    "question": "Does the container screen draw as many slots as `inventory_size` declares?",
    "look_at": "Three entities bracket this: `horse1` declares 1, `horse5` declares 5, `horse15` declares 15. Open each and count the cells actually drawn. If 1 draws 1 and 15 draws 3, the declared size controls the screen up to a ceiling. If both draw 3, the layout is fixed and the declared size never touches the screen at all. Those are different designs.",
    "askByDefault": true,
    "priorStatus": "CLOSED-NEGATIVE",
    "outcomes": [
      {
        "id": "one_for_one",
        "label": "Each draws exactly what it declared",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "ceiling",
        "label": "Small sizes draw themselves, large ones cap out -- note the ceiling",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "fixed",
        "label": "All three draw the same number regardless of what they declared",
        "verdict": "NO",
        "means": "The layout is fixed. Note the number in the note."
      },
      {
        "id": "mismatched",
        "label": "At least one draws a different count than it declared, but you could not open enough variants to say which rule applies",
        "verdict": "NO",
        "means": "Enough to know the two numbers are not the same, which is the hazard. Not enough to know whether the declared size controls the screen below a ceiling or never touches it — and those are different designs. Put the numbers you did see in the note."
      },
      {
        "id": "could_not_open",
        "label": "Could not open enough of them to compare",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 4,
    "id": "entity.container.script_writes_appear_in_screen",
    "probe": "container",
    "question": "Do contents written by script appear in the screen the player opens?",
    "look_at": "The diamond script placed in slot 0 of `horse5`, once the screen is open.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "present",
        "label": "The diamond is there",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "absent",
        "label": "The screen is empty",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "could_not_open",
        "label": "Could not open it",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 5,
    "id": "entity.container.slots_are_untyped",
    "probe": "container",
    "question": "Are the slots freely usable, or typed the way a real saddle slot is?",
    "look_at": "The open `horse5` screen. Script has already put a diamond in slot 0, so it should be visible. Try moving it between slots, and try putting something else in.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "free",
        "label": "Any item goes in any slot and stays",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "typed",
        "label": "Slots reject items, or bounce them back",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "could_not_open",
        "label": "Could not open it",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 6,
    "id": "entity.stash.holder_findable_after_chunk_unload",
    "probe": "stash",
    "question": "Is a holder entity still findable by `world.getEntity(id)` after its chunk has unloaded and reloaded?",
    "look_at": "Stash something, then walk far enough away that the chunk unloads, come back, and fetch. The probe prints the holder's coordinates, so if `getEntity` fails you can walk back to them and fetch again -- which tells \"gone forever\" apart from \"only findable when loaded\", and those two point at different designs.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "findable",
        "label": "The fetch works from wherever you are standing",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "only_when_loaded",
        "label": "The fetch fails until you walk back to the printed coordinates",
        "verdict": "NO",
        "means": "A vault design rather than a holder-per-item design."
      },
      {
        "id": "gone",
        "label": "The fetch fails even at the printed coordinates",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_unload",
        "label": "The readout says the chunk never actually unloaded",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 7,
    "id": "entity.stash.holder_findable_after_world_reload",
    "probe": "stash",
    "question": "Is a holder entity still findable by id after a full quit to title and reload?",
    "look_at": "Stash, then QUIT TO TITLE and reload, then fetch. The probe stamps a per-load session token into the stash record -- script modules are re-evaluated on every world load, so a value computed at module scope is new each session by construction. Fetch compares them and says outright whether a reload happened, so a run made in one sitting cannot be mistaken for the one that answers the question. A same-session fetch also does NOT spend the stash, because handing the item back would consume the one setup that can answer this.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "findable",
        "label": "The fetch works, and the readout confirms a reload happened",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "gone",
        "label": "The holder cannot be found after the reload",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_reload",
        "label": "The readout says no reload happened between stash and fetch",
        "verdict": "INCONCLUSIVE",
        "means": "The protocol was not followed. Quit to title, not just to the world list."
      }
    ]
  },
  {
    "index": 8,
    "id": "entity.stash.preserves_an_opaque_itemstack",
    "probe": "stash",
    "question": "Does a real ItemStack survive being moved into a holder entity's inventory and taken back out, without ever being read?",
    "look_at": "Hold an item with state the script API cannot read -- a shulker box YOU HAVE PUT THINGS IN is the right choice. Run `/scriptevent bedshock:probe stash`, then `/scriptevent bedshock:probe fetch`. Place the returned box and open it. That last step is a human one unavoidably: whether the contents came back cannot be checked from script, and that inability is the reason this route exists at all.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "intact",
        "label": "It comes back, and its contents are intact",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "returned_but_contents_unverified",
        "label": "It comes back as itself, but you did not check state the script API cannot read",
        "verdict": "YES",
        "means": "Enough to rule out the flat negative — the move-the-stack route is not broken in principle, so a codec's refusal list is not permanent. NOT enough for the case this exists for. Say in the note what you used; a gun carrying dynamic properties is a weaker witness than a shulker box you filled, because a codec could have carried the first and provably cannot carry the second."
      },
      {
        "id": "emptied",
        "label": "It comes back empty, or as a different item",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "lost",
        "label": "Nothing comes back",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_holder",
        "label": "The readout says it could not find the holder entity",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 9,
    "id": "item.creative.custom_group_nests_items",
    "probe": "menu",
    "question": "Does a shared custom `group` collapse several items into one expandable pile?",
    "look_at": "The three items labelled \"P7 grouped A/B/C\", which share one group string.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "nested",
        "label": "They collapse into one cell that expands",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "flat",
        "label": "They sit as three separate cells",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not find them",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 10,
    "id": "item.creative.hidden_by_category_none",
    "probe": "menu",
    "question": "Does an explicit `category: none` hide an item from the creative menu?",
    "look_at": "The creative menu, searching for \"P7 category none\".",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "hidden",
        "label": "It does not appear",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "visible",
        "label": "It appears",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not find the labelled items",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 11,
    "id": "item.creative.hidden_by_omitting_category",
    "probe": "menu",
    "question": "Does omitting `menu_category` entirely hide an item from the creative menu?",
    "look_at": "The creative menu. Six probe items are generated, each labelled in-game with which variant it is, so the picker screenshot is self-describing. Search for \"P7\".",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "hidden",
        "label": "The omitted-category item does not appear",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "visible",
        "label": "It appears anyway, in some default category",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not find the labelled items at all",
        "verdict": "INCONCLUSIVE",
        "means": "Check the automated existence row first. If the items do not exist, this reading is about a rejection rather than about hiding."
      }
    ]
  },
  {
    "index": 12,
    "id": "item.creative.order_follows_emission",
    "probe": "menu",
    "question": "Does the creative menu order items by the order their files are emitted?",
    "look_at": "The order the six P7 items appear in. They are emitted in the order listed in the probe config -- omitted, none, items, grouped A, B, C.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "emission_order",
        "label": "They appear in emission order",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "some_other_order",
        "label": "Some other order -- alphabetical, or by id. Note what you see",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not see enough of them to tell",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 13,
    "id": "item.durability_bar.hotbar_matches_inventory_grid",
    "probe": "ruler",
    "question": "Do the hotbar and the inventory grid draw the bar over the same rows?",
    "look_at": "The same ruler item in the hotbar and then in the inventory grid, at both damages.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "agree",
        "label": "Same rows in both",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "differ",
        "label": "Different rows -- note which, for each",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Cannot compare them reliably",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 14,
    "id": "item.durability_bar.rows_covered",
    "probe": "ruler",
    "question": "Which pixel rows of the 16x16 icon does the durability bar's dark track cover?",
    "look_at": "The ruler item in your hotbar. Every one of its 16 rows is a different colour and the bottom five are pure primaries, so you can count off which rows the bar eats. Two copies are given: one nearly pristine (long green bar) and one nearly spent (1px red). The dark track is full-width in both, and it is the track that occludes.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "rows_13_15",
        "label": "The track covers rows 13, 14 and 15 (the bottom three)",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "rows_14_15",
        "label": "The track covers rows 14 and 15 (the bottom two)",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "rows_12_15",
        "label": "The track covers rows 12 through 15 (the bottom four)",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "other_rows",
        "label": "Some other set of rows -- write it in the note",
        "verdict": "YES",
        "means": "Any definite reading is a pass. Put the exact rows in the note; the report prints it."
      },
      {
        "id": "no_track",
        "label": "No dark track appears at all",
        "verdict": "NO",
        "means": "Would contradict a rule this battery treats as established, so re-check that the items really are damaged before recording it."
      },
      {
        "id": "unreadable",
        "label": "Cannot count the rows -- too small, or the colours blur together",
        "verdict": "INCONCLUSIVE",
        "means": "The ruler's palette needs work rather than the answer being no. An earlier version used two blues 83 apart in RGB and they were indistinguishable at hotbar scale."
      }
    ]
  },
  {
    "index": 15,
    "id": "item.durability_bar.track_appears_at_damage_one",
    "probe": "ruler",
    "question": "Does the dark track appear at `damage == 1`, not just when the item is visibly worn?",
    "look_at": "The nearly-pristine ruler copy (damage 1). Look for the dark track, not the fill.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "present",
        "label": "The track is there at damage 1",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "absent",
        "label": "No track at damage 1 -- it only appears once the item is visibly worn",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Cannot tell whether that is a track or the icon's own dark row",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 16,
    "id": "item.durability.anvil_or_grindstone_can_reach_a_custom_item",
    "probe": "repair",
    "question": "Can an anvil or a grindstone alter a custom item's `damage`?",
    "look_at": "Take the probe durability item to an anvil, then to a grindstone. Does either offer to repair or strip it? If one does, take the offer and re-read the damage.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "neither",
        "label": "Neither block will touch it",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "anvil_only",
        "label": "The anvil repairs it; the grindstone does not",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "grindstone_only",
        "label": "The grindstone touches it; the anvil does not",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "both",
        "label": "Both will alter it",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not get either block to accept the item to find out",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 17,
    "id": "item.durability.mending_can_reach_a_custom_item",
    "probe": "repair",
    "question": "Does a Mending enchantment repair a custom item's `damage`?",
    "look_at": "Put Mending on the probe durability item, note the damage the probe prints, collect XP, then run the probe again to re-read it.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "repairs",
        "label": "The damage went down",
        "verdict": "YES",
        "means": "A hazard, and the mitigation is known: keep the real state in dynamic properties and treat durability as a WRITE-ONLY display cache, rewritten whenever it drifts. Nothing external can corrupt state it is not the source of."
      },
      {
        "id": "untouched",
        "label": "The damage is unchanged",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_enchant",
        "label": "Mending could not be applied to the item at all",
        "verdict": "INCONCLUSIVE",
        "means": "Worth recording in the note either way -- an item that refuses the enchantment is safe for a different reason, but this probe did not measure the one it was asking about."
      }
    ]
  },
  {
    "index": 18,
    "id": "item.durability.omitting_repairable_blocks_external_writes",
    "probe": "repair",
    "question": "Is omitting `minecraft:repairable` enough to keep anvils, grindstones and Mending away from an item's damage?",
    "look_at": "The probe items declare no `minecraft:repairable` -- deliberately, so this is testable at all. Answer this only after reading the two rows above.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "sufficient",
        "label": "Nothing external could reach the damage",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "insufficient",
        "label": "At least one route got through anyway",
        "verdict": "NO",
        "means": "Name which, in the note. The mitigation then has to be in script."
      },
      {
        "id": "unreadable",
        "label": "The rows above are not answered yet",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 19,
    "id": "item.durability.ordinary_use_consumes_it",
    "probe": "repair",
    "question": "Does using a custom item consume durability the way a tool's does?",
    "look_at": "The probe durability item's damage, before and after using it twenty times.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "unchanged",
        "label": "The damage is unchanged",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "consumed",
        "label": "The damage went up",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Could not get the item to register a use",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 20,
    "id": "item.dynamic_properties.survive_drop_and_pickup",
    "probe": "dynprops",
    "question": "Do dynamic properties survive the stack being dropped and picked up again?",
    "look_at": "The probe drops a stamped item at your feet. Pick it up, then run `/scriptevent bedshock:probe dynprops.token`. The readout says whether the token came back off the picked-up copy.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "survived",
        "label": "The readout says the token came back",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "lost",
        "label": "The readout says the token is gone",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_item",
        "label": "The follow-up says it could not find the item",
        "verdict": "INCONCLUSIVE",
        "means": "You are holding the wrong stack, or it never dropped. Re-run the probe."
      }
    ]
  },
  {
    "index": 21,
    "id": "item.dynamic_properties.survive_world_reload",
    "probe": "dynprops",
    "question": "Do dynamic properties on an ItemStack survive a full quit to title and reload?",
    "look_at": "Run `/scriptevent bedshock:probe dynprops.stamp`, then QUIT TO TITLE and reload the world, then run `/scriptevent bedshock:probe dynprops.token`. The probe stamps a per-load session token, so the readout can tell you outright whether a reload actually happened between the two halves -- a run made in one sitting reports itself as such rather than being mistaken for the real measurement.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "survived",
        "label": "The property came back, and the readout confirms a reload happened",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "lost",
        "label": "The property is gone after the reload",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "no_reload",
        "label": "The readout says no reload happened between the two halves",
        "verdict": "INCONCLUSIVE",
        "means": "The protocol was not followed, so this measures nothing. Quit to title -- leaving the world to the main menu is not always enough."
      }
    ]
  },
  {
    "index": 22,
    "id": "item.icon.animates_from_flipbook",
    "probe": "flipbook",
    "question": "Does an item atlas tile animate from a `flipbook_textures.json` entry?",
    "look_at": "The two flipbook probe items in your hotbar. They carry the SAME animation under two deliberately different spellings -- one with explicit `frames: [0,1,2,3]` and `blend_frames: false`, one omitting `frames` with `blend_frames: true`. Different in every field that could plausibly be the mistake.",
    "askByDefault": true,
    "priorStatus": "INCONCLUSIVE",
    "outcomes": [
      {
        "id": "both_cycle",
        "label": "Both icons cycle",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "one_cycles",
        "label": "One cycles, one is frozen",
        "verdict": "YES",
        "means": "Item flipbooks work and the frozen spelling was simply wrong. Note which one cycled."
      },
      {
        "id": "both_frozen",
        "label": "Both frozen on frame 0",
        "verdict": "NO",
        "means": "Still short of proof. Two negatives on two spellings look like a limit, but the definitive control is a flipbook on a BLOCK texture -- the case flipbooks are known to serve. Record this, and treat it as leaning-no rather than closed."
      },
      {
        "id": "unreadable",
        "label": "Cannot tell -- the frames may be too similar, or nothing rendered",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 23,
    "id": "item.name.glyph_alpha_is_honoured",
    "probe": "glyphs",
    "question": "Is a glyph's transparency preserved, or does it fill with a background?",
    "look_at": "The centres of the four rings in chat. Each ring is drawn on transparency.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "transparent",
        "label": "The centres read as background -- the holes are holes",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "filled",
        "label": "The centres are filled, black or white",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "absent",
        "label": "Nothing rendered",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 24,
    "id": "item.name.glyph_renders_in_colour",
    "probe": "glyphs",
    "question": "Do custom font glyph pages render in full colour rather than being flattened?",
    "look_at": "The four rings printed into chat. They are authored as #d94f4f, #4fd96a, #4f7fd9 and #ffffff -- red, green, blue, white. Vanilla's own pages are near-monochrome, which is the only reason this is in doubt.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "full_colour",
        "label": "All four render in their own colours",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "flattened",
        "label": "They render, but flattened to white or grey",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "absent",
        "label": "Nothing renders where the glyphs should be",
        "verdict": "INCONCLUSIVE",
        "means": "The glyph page did not load. That is an apparatus fault, not an answer."
      }
    ]
  },
  {
    "index": 25,
    "id": "item.name.glyph_renders_in_item_name",
    "probe": "glyphs",
    "question": "Does a glyph render in an ITEM's name and in the actionbar, not only in chat?",
    "look_at": "The glyph probe item in your hotbar -- its nameTag carries all four rings -- and the actionbar line the probe prints. Compare both against the chat line.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "all_three",
        "label": "Chat, item name and actionbar all show the coloured rings",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "chat_only",
        "label": "Chat shows them; the item name or the actionbar does not",
        "verdict": "NO",
        "means": "Note which surface failed -- they are separate renderers and may differ."
      },
      {
        "id": "unreadable",
        "label": "Could not compare all three",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 26,
    "id": "render.attachable.accepts_vanilla_hold_animations",
    "probe": "attachable_pose",
    "question": "Will a custom item's attachable accept the vanilla hold animations and be posed into the hand?",
    "look_at": "A separate rig carrying `animations` plus a `scripts.animate` list selecting on `c.is_first_person`, copied from the vanilla resource pack's own attachables. Hold it and check both persons. Do NOT fold this into the flag rig -- posing those flags into the hand would make them small and half-occluded, which is the exact failure that rig has already been repaired for twice.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "posed_both",
        "label": "It sits in the hand, and first and third person differ as vanilla's do",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "posed_one",
        "label": "It is posed in one person but not the other",
        "verdict": "YES",
        "means": "Partial. Note which person worked."
      },
      {
        "id": "unposed",
        "label": "It still sits at the model origin, unaffected",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "nothing",
        "label": "Nothing renders now, where the unanimated rig did",
        "verdict": "INCONCLUSIVE",
        "means": "The animation reference is probably wrong rather than unsupported. Read the vanilla identifiers out of the vanilla resource pack rather than trusting one written from memory."
      }
    ]
  },
  {
    "index": 27,
    "id": "render.attachable.anchor_is_on_the_body",
    "probe": "attachable",
    "question": "Is an attachable's anchor on the player's body rather than in the hand?",
    "look_at": "The probe geometry in third person, from an over-the-shoulder camera. The probe's cubes are authored deliberately offset -- up and back -- so where they land tells you where the anchor is.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "on_body",
        "label": "The geometry is positioned relative to the body, not the hand",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "in_hand",
        "label": "It follows the hand",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Nothing rendered, or could not get a third-person view",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 28,
    "id": "render.attachable.draws_on_custom_item",
    "probe": "attachable",
    "question": "Does a custom item render an attachable at all?",
    "look_at": "Hold the minimal attachable probe item. One geometry, one texture, one material, one controller -- no arrays, no Molang, no `part_visibility`, no durability. Expect a plain magenta cube. Nothing else in the pack is #ff00ff, and Bedrock's own missing-texture is a black/magenta CHECKER rather than a solid field, so the two are distinguishable. Check third person as well as first.",
    "askByDefault": false,
    "priorStatus": "SETTLED",
    "outcomes": [
      {
        "id": "renders",
        "label": "A magenta cube appears, and third person shows it plainly as a cube",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "renders_but_engulfs",
        "label": "The whole screen goes magenta in first person",
        "verdict": "YES",
        "means": "Still an unambiguous pass. The hand pivot is essentially at the camera in first person, so geometry near the anchor swallows the view. Confirm in third person and record it -- this is what happened the first time, and the failure that would have killed the route was INVISIBLE, not oversized."
      },
      {
        "id": "nothing",
        "label": "Nothing renders, in either person",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "checker",
        "label": "A black-and-magenta checkerboard",
        "verdict": "INCONCLUSIVE",
        "means": "That is Bedrock's missing-texture, so the attachable resolved but its texture did not. An apparatus fault, not an answer."
      }
    ]
  },
  {
    "index": 29,
    "id": "render.attachable.reads_held_item_durability",
    "probe": "attachable",
    "question": "Can a render controller on an attachable read the durability of the item it draws?",
    "look_at": "Two items, identical but for damage -- A at 5, B at 6. Hold each in turn and read the four flags. THE READING IS DIFFERENTIAL, and it has to be: with `max_durability` at 2048 and 2048 mod 4 = 0, an UNDAMAGED item shows the same colours as a blind query, so an absolute reading of one item cannot answer this. A live query MUST change colour between A and B; a blind one cannot. Bone 3 is a control wired to the literal `2` -- if it is not BLUE on both, the apparatus is broken and no other bone means anything.",
    "askByDefault": true,
    "priorStatus": "CLOSED-NEGATIVE",
    "outcomes": [
      {
        "id": "flags_move",
        "label": "Bones 0 and 1 change colour between item A and item B",
        "verdict": "YES",
        "means": "The queries are live. Note which colours, for each item."
      },
      {
        "id": "flags_identical",
        "label": "All four bones look identical on A and B, with the control BLUE on both",
        "verdict": "NO",
        "means": "The queries resolve to 0 -- they resolve, they just never see an item. The one thing that would overturn this is the damage never reaching the items, which is why the probe writes the damage, reads it back, and stamps the value it read into each item's name. If those two names come back identical, this reading is void."
      },
      {
        "id": "control_wrong",
        "label": "The control bone is not BLUE",
        "verdict": "INCONCLUSIVE",
        "means": "The apparatus is broken. Fix it before recording anything."
      },
      {
        "id": "cannot_see_all_four",
        "label": "Fewer than four flags are visible",
        "verdict": "INCONCLUSIVE",
        "means": "Two flags out of four is not half an answer. Without knowing WHICH bones drew, a blue could be the control working or bone 0 landing on blue by arithmetic, and those point opposite ways. Move the geometry and re-run."
      }
    ]
  },
  {
    "index": 30,
    "id": "render.attachable.several_controllers_at_once",
    "probe": "attachable",
    "question": "Can several render controllers run on one attachable simultaneously?",
    "look_at": "How many of the four flags draw at once, and whether there is any z-fighting or ordering artefact between them.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "all_four",
        "label": "All four flags draw cleanly",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "some_with_artefacts",
        "label": "All four draw but there is z-fighting or ordering trouble",
        "verdict": "YES",
        "means": "Layering works but needs care. Describe the artefact in the note."
      },
      {
        "id": "only_one",
        "label": "Only one controller's geometry ever draws",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "unreadable",
        "label": "Nothing drew, or the view could not show all four",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 31,
    "id": "ui.form.button_icon_resolves_a_bare_atlas_key",
    "probe": "formicon",
    "question": "Does a bare atlas short-name work where a path is expected?",
    "look_at": "Button 3, which passes a bare atlas key rather than a path. Expected to fail.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "draws",
        "label": "It draws",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "blank",
        "label": "It does not draw",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "control_blank",
        "label": "The vanilla control did not draw either",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  },
  {
    "index": 32,
    "id": "ui.form.button_icon_resolves_an_unindexed_path",
    "probe": "formicon",
    "question": "Does `ActionFormData.button(text, iconPath)` draw a texture that has NO `item_texture.json` entry?",
    "look_at": "Button 1 in the form the probe opens. Its texture is written to `textures/probe/` and deliberately LEFT OUT of `item_texture.json` -- its absence there is the exact thing being ruled out. Button 2 is a vanilla path and is the control: if IT does not draw, the mechanism is broken and button 1 means nothing.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "draws",
        "label": "Button 1 draws its icon, and so does the vanilla control",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "blank",
        "label": "The vanilla control draws but button 1 is blank",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "control_blank",
        "label": "The vanilla control does not draw either",
        "verdict": "INCONCLUSIVE",
        "means": "The apparatus is broken. Nothing else in this probe is readable."
      }
    ]
  },
  {
    "index": 33,
    "id": "ui.form.missing_icon_is_visually_distinct",
    "probe": "formicon",
    "question": "Does a deliberately wrong icon path render as a broken-texture mark, or as nothing?",
    "look_at": "Button 4, which points at a path that deliberately does not exist.",
    "askByDefault": true,
    "priorStatus": "OPEN",
    "outcomes": [
      {
        "id": "broken_mark",
        "label": "It shows a missing-texture mark",
        "verdict": "YES",
        "means": ""
      },
      {
        "id": "blank",
        "label": "It renders as nothing, the same as a button with no icon at all",
        "verdict": "NO",
        "means": ""
      },
      {
        "id": "control_blank",
        "label": "The vanilla control did not draw either",
        "verdict": "INCONCLUSIVE",
        "means": ""
      }
    ]
  }
];
export const SOLVES: SolveSpec[] = [
  {
    "id": "physics.falling_block.gravity_curve",
    "probe": "fallcurve",
    "unit": "blocks_per_tick",
    "direction": "maximum",
    "from": -4,
    "to": 0,
    "tolerance": 0.01
  },
  {
    "id": "physics.falling_block.min_clearance_under_a_falling_anvil",
    "probe": "anvilgap",
    "unit": "blocks",
    "direction": "minimum",
    "from": 0,
    "to": 8,
    "tolerance": 0.6
  },
  {
    "id": "physics.knockback.blocks_per_unit",
    "probe": "knockback",
    "unit": "blocks_per_unit",
    "direction": "maximum",
    "from": 0,
    "to": 20,
    "tolerance": 0.1
  },
  {
    "id": "physics.throw.item_travel_distance",
    "probe": "throw",
    "unit": "blocks",
    "direction": "maximum",
    "from": 0,
    "to": 32,
    "tolerance": 0.25
  }
];
