// GENERATED by tools/gen/pack.ts — do not edit.
// Ids and apparatus parameters, so the runtime and the emitted files cannot disagree.

export interface MenuId { id: string; label: string; category?: string; group?: string }
export interface ContainerId { id: string; container_type: string; size: number }
export interface DurabilityId { declared: number; id: string }

export const NAMESPACE = "bedshock";
export const PACK_VERSION = "0.1.0";

export const IDS: {
  durability: DurabilityId[];
  ruler: string;
  glyph: string;
  dynprop: string;
  offhand_custom: string;
  repair: string;
  flipbook: string[];
  menu: MenuId[];
  containers: ContainerId[];
} = {
  "durability": [
    {
      "declared": 2031,
      "id": "bedshock:probe_dur_2031"
    },
    {
      "declared": 4096,
      "id": "bedshock:probe_dur_4096"
    },
    {
      "declared": 16384,
      "id": "bedshock:probe_dur_16384"
    },
    {
      "declared": 32767,
      "id": "bedshock:probe_dur_32767"
    },
    {
      "declared": 32768,
      "id": "bedshock:probe_dur_32768"
    },
    {
      "declared": 65535,
      "id": "bedshock:probe_dur_65535"
    }
  ],
  "ruler": "bedshock:probe_ruler",
  "repair": "bedshock:probe_repair",
  "glyph": "bedshock:probe_glyph",
  "dynprop": "bedshock:probe_dynprop",
  "offhand_custom": "bedshock:probe_offhand_ok",
  "flipbook": [
    "bedshock:probe_flip_a",
    "bedshock:probe_flip_b"
  ],
  "menu": [
    {
      "id": "bedshock:probe_menu_omitted",
      "label": "P7 omitted (no menu_category)"
    },
    {
      "id": "bedshock:probe_menu_none",
      "label": "P7 category none",
      "category": "none"
    },
    {
      "id": "bedshock:probe_menu_items",
      "label": "P7 category items",
      "category": "items"
    },
    {
      "id": "bedshock:probe_menu_grouped_a",
      "label": "P7 grouped A",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    },
    {
      "id": "bedshock:probe_menu_grouped_b",
      "label": "P7 grouped B",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    },
    {
      "id": "bedshock:probe_menu_grouped_c",
      "label": "P7 grouped C",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    }
  ],
  "containers": [
    {
      "id": "bedshock:probe_box_chest5",
      "container_type": "chest",
      "size": 5
    },
    {
      "id": "bedshock:probe_box_horse5",
      "container_type": "horse",
      "size": 5
    },
    {
      "id": "bedshock:probe_box_horse1",
      "container_type": "horse",
      "size": 1
    },
    {
      "id": "bedshock:probe_box_horse15",
      "container_type": "horse",
      "size": 15
    }
  ]
};

export const PARAMS = {
  "durability": {
    "ceilings": [
      2031,
      4096,
      16384,
      32767,
      32768,
      65535
    ]
  },
  "ruler": {
    "max_durability": 2048,
    "damage_samples": [
      1,
      2046
    ]
  },
  "glyphs": {
    "page": "E2",
    "swatches": [
      "#d94f4f",
      "#4fd96a",
      "#4f7fd9",
      "#ffffff"
    ]
  },
  "form_icons": {
    "unindexed_path": "textures/probe/icon_unindexed",
    "vanilla_path": "textures/items/apple",
    "atlas_key": "apple",
    "missing_path": "textures/probe/does_not_exist"
  },
  "menu_variants": [
    {
      "id": "omitted",
      "label": "P7 omitted (no menu_category)"
    },
    {
      "id": "none",
      "label": "P7 category none",
      "category": "none"
    },
    {
      "id": "items",
      "label": "P7 category items",
      "category": "items"
    },
    {
      "id": "grouped_a",
      "label": "P7 grouped A",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    },
    {
      "id": "grouped_b",
      "label": "P7 grouped B",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    },
    {
      "id": "grouped_c",
      "label": "P7 grouped C",
      "category": "items",
      "group": "itemGroup.name.probe_group"
    }
  ],
  "flipbook": {
    "frames": 4,
    "ticks_per_frame": 8
  },
  "containers": [
    {
      "id": "chest5",
      "container_type": "chest",
      "size": 5
    },
    {
      "id": "horse5",
      "container_type": "horse",
      "size": 5
    },
    {
      "id": "horse1",
      "container_type": "horse",
      "size": 1
    },
    {
      "id": "horse15",
      "container_type": "horse",
      "size": 15
    }
  ],
  "offhand": {
    "permitted_item": "minecraft:shield",
    "arbitrary_items": [
      "minecraft:diamond",
      "minecraft:diamond_pickaxe",
      "minecraft:stone",
      "minecraft:bread"
    ],
    "settle_ticks": 60
  },
  "falling_block": {
    "block": "minecraft:anvil",
    "drop_height": 12,
    "watch_ticks": 40,
    "lane": 0
  },
  "anvilgap": {
    "block": "minecraft:anvil",
    "obstruction": "minecraft:stone",
    "plane_height": 4,
    "drop_height": 6,
    "vacate_ticks": 6,
    "watch_ticks": 80,
    "repeats": 2,
    "max_trials": 40,
    "lane": 6
  },
  "throw": {
    "item": "minecraft:stick",
    "run_length": 24,
    "headroom": 4,
    "release_height": 1,
    "impulse_forward": 0.6,
    "impulse_up": 0.25,
    "rest_speed": 0.003,
    "rest_ticks": 8,
    "moved_at_least": 0.05,
    "watch_ticks": 200,
    "samples": 5,
    "spread": 0.5,
    "lane": 12
  },
  "knockback": {
    "subject": "bedshock:probe_box_chest5",
    "subject_stack": "minecraft:stick",
    "units": 1,
    "run_length": 16,
    "headroom": 4,
    "rest_step": 0.002,
    "rest_ticks": 8,
    "moved_by_ticks": 20,
    "watch_ticks": 120,
    "samples": 5,
    "spread": 0.2,
    "lane": 20
  }
} as const;
export const GLYPHS = ["","","",""];
