/**
 * Rendering the ledger as Markdown.
 *
 * `docs/CAPABILITIES.md` in the repository this grew out of was a hand-maintained document,
 * and it was a good one -- but every fact in it was a copy, and a copy can rot. Worse, its
 * loudest rule was "do not edit an expectation to make a probe quiet", which is a rule that
 * nothing but discipline could enforce, because the expectation and the answer lived in the
 * same editable file.
 *
 * Here the document is output. There is no expectation to edit: a status is a function of
 * observations, and to change one you have to record a measurement. What a person writes by
 * hand is the QUESTION -- what it asks, which decision it blocks, how to tell two outcomes
 * apart -- and that is exactly the part that does not go stale.
 *
 * Two shapes come out of here:
 *
 *   MATRIX (`bedshock report`)   every capability x every version the ledger knows about.
 *                                The file to read when asking "when did this become possible".
 *   VERSION (`--version X`)      one version, in full, with evidence. The releasable artifact
 *                                for a particular Minecraft build.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Capability, Observation, Status } from './types.ts';
import type { Catalog } from './catalog.ts';
import { compareVersions, resolveWithDeps, statusAt, versionsInLedger } from './ledger.ts';
import { DOCS_DIR } from './paths.ts';

const GENERATED_BY = 'tools/report.ts';

/** Compact marks for the matrix. Legible in a fixed-width table, which prose is not. */
const MARK: Record<Status, string> = {
  SETTLED: '**yes**',
  'CLOSED-NEGATIVE': '**no**',
  OPEN: '·',
  INCONCLUSIVE: '?',
  DRIFT: '**DRIFT**',
  UNDERMINED: 'yes\\*',
};

const BADGE: Record<Status, string> = {
  SETTLED: '`SETTLED`',
  'CLOSED-NEGATIVE': '`CLOSED-NEGATIVE`',
  OPEN: '`OPEN`',
  INCONCLUSIVE: '`INCONCLUSIVE`',
  DRIFT: '`DRIFT`',
  UNDERMINED: '`UNDERMINED`',
};

function esc(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n\s*/g, ' ').trim();
}

function header(title: string, subtitle: string): string[] {
  return [
    `# ${title}`,
    '',
    `<!-- GENERATED BY ${GENERATED_BY} — DO NOT EDIT.`,
    '     The questions are hand-written in content/capabilities/*.yaml.',
    '     The answers are append-only in ledger/observations.jsonl.',
    '     Run `npm run report` to rebuild this file. -->',
    '',
    subtitle,
    '',
  ];
}

// ---------------------------------------------------------------------------
// The matrix
// ---------------------------------------------------------------------------

export function renderMatrix(catalog: Catalog, observations: Observation[]): string {
  const versions = versionsInLedger(observations);
  const out: string[] = [];

  out.push(
    ...header(
      'What Bedrock can actually do',
      'A capability matrix for the things the official docs do not cover and the surrounding web ' +
        'content covers wrongly. **Read this before designing anything that depends on a row in it.**',
    ),
  );

  out.push(
    'Every row is a question about Bedrock, and every column is a Minecraft version. A cell is an',
    'answer *on that version* — which is the axis that matters, because these answers are',
    'version-specific and Bedrock changes them without notice.',
    '',
    '| Mark | Meaning | What you may do with it |',
    '|---|---|---|',
    '| **yes** | Measured, and the answer is yes | Build on it. Cite it by id |',
    '| **no** | Measured, and the answer is no | The idea is dead on that version. The row exists so nobody reproposes it |',
    '| · | Never measured on that version | Do not build on it. A plan resting on this needs a fallback |',
    '| ? | Measured, and the apparatus could not be trusted | Not a soft no — the probe needs work before the row means anything |',
    '| **DRIFT** | Two runs on the *same version* disagree | The loudest verdict. Either the game changed under a version number or a probe was edited into lying |',
    '| yes\\* | Settled, but downstream of something still open | The rig may have measured the instrument rather than the game. Read its dependency first |',
    '',
    'A blank column for a new version is not a finding — it is a battery that has not been run',
    'there yet. `bedshock run --open` re-runs only the rows still unanswered, which is the whole',
    'point of keeping the question and the answer in separate files: **the test for a capability',
    'that does not exist yet is written before it exists**, and re-running it on each new version',
    'is how you find out the day it starts working.',
    '',
  );

  // --- the glance table ---
  out.push('## Status at a glance', '');
  if (versions.length === 0) {
    out.push('*The ledger is empty. Run `bedshock run` to measure something.*', '');
  } else {
    out.push(`| Capability | ${versions.join(' | ')} |`);
    out.push(`|---|${versions.map(() => '---').join('|')}|`);
    for (const [domain, group] of catalog.byDomain) {
      out.push(`| **${domain}** | ${versions.map(() => '').join(' | ')} |`);
      for (const cap of group.capabilities) {
        const cells = versions.map((v) => {
          if (cap.method === 'derived') return '—';
          const s = resolveWithDeps(cap, v, observations, catalog);
          return s.inherited ? '' : MARK[s.status];
        });
        out.push(`| \`${cap.id}\` | ${cells.join(' | ')} |`);
      }
    }
    out.push(
      '',
      '`—` is a **derived** row: established by reading what the engine or our own emitted files do,',
      'rather than by a probe. Those do not vary per version in any way this battery could detect,',
      'so they are recorded once and cited, not re-measured.',
      '',
      'An empty cell in a version column means nothing was measured **at that exact version**. It is',
      'not the same as `·`, which is a capability nothing has ever answered anywhere.',
      '',
    );
  }

  // --- anything shouting ---
  const alarms: string[] = [];
  for (const cap of catalog.capabilities) {
    for (const v of versions) {
      const s = statusAt(cap, v, observations);
      if (s.status === 'DRIFT') alarms.push(`- **\`${cap.id}\`** on ${v} — ${s.conflict}`);
    }
  }
  if (alarms.length) {
    out.push(
      '## !! Recorded answers that no longer hold',
      '',
      'The only verdict that means *this document is now wrong*. Everything designed on these rows',
      'is suspect until they are re-measured.',
      '',
      ...alarms,
      '',
    );
  }

  // --- per-domain detail ---
  for (const [domain, group] of catalog.byDomain) {
    out.push(`## ${domain}`, '');
    if (group.about) out.push(esc(group.about), '');
    for (const cap of group.capabilities) {
      out.push(...renderCapability(cap, versions, observations, catalog));
    }
  }

  out.push(...renderFooter(catalog, observations));
  return out.join('\n');
}

function renderCapability(
  cap: Capability,
  versions: string[],
  observations: Observation[],
  catalog: Catalog,
): string[] {
  const out: string[] = [];
  out.push(`### \`${cap.id}\``, '');
  out.push(`**${esc(cap.question)}**`, '');
  out.push(`*Decides:* ${esc(cap.decides)}`, '');

  const meta: string[] = [`method: \`${cap.method}\``];
  if (cap.probe) meta.push(`probe: \`${cap.probe}\``);
  if (cap.legacy) meta.push(`formerly: ${cap.legacy}`);
  if (cap.depends_on?.length) meta.push(`rests on: ${cap.depends_on.map((d) => `\`${d}\``).join(', ')}`);
  out.push(`<sub>${meta.join(' · ')}</sub>`, '');

  if (cap.method === 'derived') {
    out.push(`*Established by:* ${esc(cap.established_by ?? '')}`, '');
  } else {
    const measured = versions.filter((v) => statusAt(cap, v, observations).status !== 'OPEN');
    if (measured.length === 0) {
      out.push('**Never measured.** This row is a guess, however confident the prose around it sounds.', '');
      if (cap.look_at) out.push(`*To answer it:* ${esc(cap.look_at)}`, '');
    } else {
      out.push('| Version | Answer | How | Evidence |', '|---|---|---|---|');
      for (const v of measured) {
        const s = resolveWithDeps(cap, v, observations, catalog);
        const top = s.observations[0]!;
        const how = `${top.method}, ${top.platform}`;
        const evidence = [top.evidence, top.note && `*${top.note}*`, s.conflict && `**${s.conflict}**`]
          .filter(Boolean)
          .join(' — ');
        out.push(`| ${v} | ${BADGE[s.status]} | ${how} | ${esc(evidence || '—')} |`);
      }
      out.push('');
      const withMeasurement = measured
        .map((v) => statusAt(cap, v, observations).observations[0])
        .filter((o): o is Observation => !!o?.measurement);
      if (withMeasurement.length) {
        out.push('<details><summary>What the probe actually saw</summary>', '');
        for (const o of withMeasurement) {
          out.push('```json', `// ${o.version} · run ${o.run}`, JSON.stringify(o.measurement, null, 2), '```', '');
        }
        out.push('</details>', '');
      }
    }
  }

  if (cap.notes) out.push(`> ${esc(cap.notes)}`, '');
  if (cap.method === 'observed' && cap.outcomes) {
    out.push('<details><summary>The answer space this probe can distinguish</summary>', '');
    out.push('| Outcome | Means | |', '|---|---|---|');
    for (const o of cap.outcomes) {
      out.push(`| \`${o.id}\` | ${esc(o.label)} | ${o.verdict}${o.means ? ` — ${esc(o.means)}` : ''} |`);
    }
    out.push('', '</details>', '');
  }
  return out;
}

// ---------------------------------------------------------------------------
// One version, in full
// ---------------------------------------------------------------------------

export function renderVersionReport(catalog: Catalog, observations: Observation[], version: string): string {
  const out: string[] = [];
  const rows = catalog.capabilities
    .filter((c) => c.method !== 'derived')
    .map((c) => resolveWithDeps(c, version, observations, catalog));

  const counted = (s: Status): number => rows.filter((r) => r.status === s).length;
  const measuredHere = rows.filter((r) => !r.inherited && r.status !== 'OPEN');
  const runs = [...new Set(measuredHere.flatMap((r) => r.observations.map((o) => o.run)))];
  const apis = [...new Set(measuredHere.flatMap((r) => r.observations.map((o) => o.api).filter(Boolean)))];
  const dates = measuredHere.flatMap((r) => r.observations.map((o) => o.at)).sort();

  out.push(
    ...header(
      `Bedrock ${version} — capability report`,
      `What this battery could establish about Minecraft Bedrock **${version}**.`,
    ),
  );

  out.push(
    '| | |',
    '|---|---|',
    `| Version | ${version} |`,
    `| Script API | ${apis.length ? apis.join(', ') : '—'} |`,
    `| Measured | ${dates.length ? `${dates[0]!.slice(0, 10)} … ${dates.at(-1)!.slice(0, 10)}` : '—'} |`,
    `| Runs | ${runs.length ? runs.join(', ') : '—'} |`,
    `| Capabilities asked | ${rows.length} |`,
    `| Answered here | ${measuredHere.length} |`,
    '',
    `**${counted('SETTLED')} yes · ${counted('CLOSED-NEGATIVE')} no · ${counted('OPEN')} unanswered` +
      ` · ${counted('INCONCLUSIVE')} inconclusive · ${counted('DRIFT')} drifted**`,
    '',
  );

  const inherited = rows.filter((r) => r.inherited);
  if (inherited.length) {
    out.push(
      `${inherited.length} row(s) below carry an answer measured on an **older** version and not`,
      're-checked here. That is evidence, not a measurement: Bedrock removes things, and the only',
      'thing that says so is a run. They are marked *(inherited)*.',
      '',
    );
  }

  for (const [domain, group] of catalog.byDomain) {
    const domainRows = group.capabilities.filter((c) => c.method !== 'derived');
    if (!domainRows.length) continue;
    out.push(`## ${domain}`, '', '| Capability | Answer | Question |', '|---|---|---|');
    for (const cap of domainRows) {
      const s = resolveWithDeps(cap, version, observations, catalog);
      const badge = BADGE[s.status] + (s.inherited ? ` *(inherited from ${s.measuredAt})*` : '');
      out.push(`| \`${cap.id}\` | ${badge} | ${esc(cap.question)} |`);
    }
    out.push('');
  }

  const stillOpen = rows.filter((r) => r.status === 'OPEN' || r.status === 'INCONCLUSIVE');
  if (stillOpen.length) {
    out.push(
      '## What this version has not answered',
      '',
      'Nothing here is a negative result. These are questions the battery is ready to ask and',
      'nobody has run yet on this version — which is the state a capability is in for as long as',
      'it takes the game to grow it.',
      '',
    );
    for (const r of stillOpen) {
      out.push(`- \`${r.capability.id}\` — ${esc(r.capability.question)}`);
      if (r.capability.look_at) out.push(`  <br><sub>${esc(r.capability.look_at)}</sub>`);
    }
    out.push('');
  }

  const derived = catalog.capabilities.filter((c) => c.method === 'derived');
  if (derived.length) {
    out.push(
      '## Settled without a probe',
      '',
      'Established well enough not to spend a battery slot on — by reading what the engine does, or',
      'by an API that does not exist. Recorded so nobody re-derives them, and so a future',
      'contradiction is visible as a contradiction.',
      '',
      '| Claim | Established by | Consequence |',
      '|---|---|---|',
    );
    for (const c of derived) {
      out.push(`| ${esc(c.question)} | ${esc(c.established_by ?? '')} | ${esc(c.decides)} |`);
    }
    out.push('');
  }

  return out.join('\n');
}

function renderFooter(catalog: Catalog, observations: Observation[]): string[] {
  const versions = versionsInLedger(observations);
  return [
    '---',
    '',
    '## How to change something in this file',
    '',
    'You cannot, directly — it is generated. Which is the point:',
    '',
    '**To add a question**, write a capability into `content/capabilities/<domain>.yaml`. It needs',
    'a `decides` saying which decision it blocks; a capability with no decision behind it is one',
    'nobody will read the result of. If it is `observed`, it also needs its answer space written',
    'out — `outcomes`, including one meaning *I could not read it*, because a rig that did not',
    'render must not be recordable as a finding.',
    '',
    '**To answer one**, run the battery. `bedshock run` for the automated rows, `bedshock amend`',
    'for the ones only eyes can settle. Both append to `ledger/observations.jsonl`.',
    '',
    '**To challenge an answer**, re-run its probe and record what you got. A row changes when a',
    'measurement changes it, never when it becomes inconvenient — and because the ledger is',
    'append-only, the old answer stays visible beside the new one. If the game itself changed, the',
    'battery says `DRIFT` before anyone has to argue.',
    '',
    '**Cite these ids, do not restate them.** Write `` `item.max_durability.int16_ceiling` `` rather',
    'than repeating the finding. A restatement is a copy that can rot; a citation cannot. Source in',
    'other repositories can carry `@requires bedshock:<id>` and `bedshock check` will fail the build',
    'if the cited row is not settled at that pack\'s `min_engine_version` — so a design can never',
    'quietly come to rest on a guess.',
    '',
    `<sub>${catalog.capabilities.length} capabilities · ${observations.length} observations · ` +
      `${versions.length} version(s): ${versions.join(', ') || 'none'}</sub>`,
    '',
  ];
}

// ---------------------------------------------------------------------------

export function writeReports(catalog: Catalog, observations: Observation[]): string[] {
  mkdirSync(DOCS_DIR, { recursive: true });
  const written: string[] = [];

  const matrix = join(DOCS_DIR, 'CAPABILITIES.md');
  writeFileSync(matrix, renderMatrix(catalog, observations) + '\n');
  written.push(matrix);

  const versionDir = join(DOCS_DIR, 'versions');
  mkdirSync(versionDir, { recursive: true });
  for (const v of versionsInLedger(observations)) {
    const path = join(versionDir, `${v}.md`);
    writeFileSync(path, renderVersionReport(catalog, observations, v) + '\n');
    written.push(path);
  }

  const index = versionsInLedger(observations)
    .slice()
    .sort((a, b) => compareVersions(b, a))
    .map((v) => `- [Bedrock ${v}](${v}.md)`);
  writeFileSync(
    join(versionDir, 'README.md'),
    ['# Per-version reports', '', 'Generated. One file per Minecraft version the ledger has an answer for.', '', ...index, ''].join('\n'),
  );
  written.push(join(versionDir, 'README.md'));

  return written;
}
